apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST

  - name: Postgres Datastore DB
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    user: postgres
    basicAuth: false
    isDefault: false
    editable: true
    secureJsonData:
      password: mysecretpassword
    jsonData:
      connMaxLifetime: 14400
      database: data
      maxIdleConns: 3
      maxIdleConnsAuto: true
      maxOpenConns: 3
      sslmode: disable
