global:
  scrape_interval:     15s
  evaluation_interval: 15s
  query_log_file: /prometheus/query.log

scrape_configs:
  - job_name: monitoring
    static_configs:
        - targets: ["monitoring:9090"]
  - job_name: export-db-metrics
    static_configs:
      - targets: ["export-db-metrics:9187"]
  - job_name: store
    static_configs:
      - targets: [ 'store:8080' ]
