# Optimize postgres settings for SSD.
# Settings below are for a DB "server" with 16 GB of memory, and nothing else running on it.
shared_buffers = 4GB  # Should be 25% of memory on the DB "server"
random_page_cost = 1.1
effective_io_concurrency = 200
effective_cache_size = 12GB  # Should be 75% of memory on the DB "server"
work_mem = 16MB

# postgres-exporter
shared_preload_libraries = 'pg_cron,pg_stat_statements'
track_activity_query_size = 2048
pg_stat_statements.track = 'all'
pg_stat_statements.max = 10000
pg_stat_statements.save = 'on'
