name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build docker containers
        run: docker compose build

      - name: Start docker stack
        run: docker compose up -d

      - name: Test loader runs without errors
        run: docker compose run --rm loader

      - name: Integration test
        run: docker compose run --rm integration

      - name: Test client runs without errors
        run: docker compose run --rm client

      - name: Run load test
        run: |
          python --version
          pip install -r load-test/requirements.txt
          python -m grpc_tools.protoc --proto_path=datastore/protobuf datastore.proto --python_out=load-test --grpc_python_out=load-test
          cd load-test
          locust --headless -u 5 -r 1 --run-time 60 --only-summary --csv store

      - name: Archive load test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: performance
          path: load-test/store_*.csv

      - name: Print results
        run: |
          pip install csvkit
          echo "## FindTimeSeries average response time: $(csvgrep -c 2 -r "FindTimeSeries" load-test/store_stats.csv | csvcut -c 6 | tail -n +2) ms" >> $GITHUB_STEP_SUMMARY
          echo "## GetObservations average response time: $(csvgrep -c 2 -r "GetObservations" load-test/store_stats.csv | csvcut -c 6 | tail -n +2) ms" >> $GITHUB_STEP_SUMMARY
          csvlook load-test/store_stats.csv >> $GITHUB_STEP_SUMMARY
          csvlook load-test/store_stats_history.csv >> $GITHUB_STEP_SUMMARY
          csvlook load-test/store_failures.csv >> $GITHUB_STEP_SUMMARY

      - name: Cleanup
        if: always()
        run: docker compose down --volumes
