name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build docker containers
        run: docker compose build

      - name: Start docker stack
        run: docker compose up -d

      - name: Test loader runs without errors
        run: docker compose run --rm loader

      - name: Integration test
        run: docker compose run --rm integration

      - name: Test client runs without errors
        run: docker compose run --rm client

      - name: Set up for load test
        run: |
          python --version
          pip install -r load-test/requirements.txt
          python -m grpc_tools.protoc --proto_path=datastore/protobuf datastore.proto --python_out=load-test --grpc_python_out=load-test

      - name: Run load test
        uses: apardo04/locust-github-action@master
        run:
        with:
          LOCUSTFILE: "load-test/locustfile.py"
          USERS: "1"
          RATE: "1"
          RUNTIME: "10s"

      - name: Cleanup
        if: always()
        run: docker compose down --volumes
