name: cpp-linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: './src/esoh/ingest/bufr'
        extensions: 'h,cpp'
        clangFormatVersion: 14
        style: allman
